### ISSUE TITLE
初期盤面を取得できない

### ISSUE THREAD

**Issue by MiraiHattori** [future731/python-2048#1]
そういえば初期盤面の取得インターフェースがない

**Comment by kyawawa** [comment]
全て0 or 現在の盤面を返すメソッドをGameに実装して，execOnce内でも使いつつinitGameでの返り値にする？

別issueですが，盤面初期化時にplaceTwoOrFourを1回しか呼んでいなくて，1ターン目に1個しか埋まっていないなんてことはない？

**Comment by MiraiHattori** [comment]
それが正しそうです

別issue，たしかに間違った実装になってますね．2回呼ぶことにします．．
あと，そのへんのコードを見ていてexplicit Board()のコンストラクタ内はthis->clear()にするのが正しそうだなぁと思ってます
